general.import = [
    "~/.config/alacritty/themes/themes/tokyo_night_storm.toml"
]

[window]
opacity = 0.8
blur = true
decorations = "None"
padding = { x = 10, y = 10 }

[font]
normal.family = "FiraCode Nerd Font"

size = 12

[terminal]
shell = "cmd"
