version = 2
final_space = true
console_title_template = "I use NixOS btw"

[[blocks]]
type = "rprompt"
overflow = "hidden"

  [[blocks.segments]]
  type = "executiontime"
  style = "plain"
  foreground = "yellow"
  background = "transparent"

    [blocks.segments.properties]
    style = "roundrock"

  [[blocks.segments]]
  type = "os"
  style = "plain"
  foreground = "p:blue"
  background = "transparent"
  template = " {{ if .WSL }}I use {{ .Icon }}  btw {{ end }}"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "session"
  style = "diamond"
  trailing_diamond = ""
  foreground = "p:white"
  background = "p:grey"
  template = " {{ if .SSHSession }} {{ end }}{{ .UserName }} "

  [[blocks.segments]]
  type = "path"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = ""
  foreground = "p:white"
  background = "p:dark_blue"
  template = "  {{ path .Path .Location }} "

    [blocks.segments.properties]
    style = "full"

  [[blocks.segments]]
  type = "git"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = ""
  foreground = "p:black"
  foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}",
  "{{ if gt .Ahead 0 }}p:white{{ end }}"
]
  background = "p:orange"
  background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}",
  "{{ if gt .Ahead 0 }}#49416D{{ end }}",
  "{{ if gt .Behind 0 }}#7A306C{{ end }}"
]
  template = " {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} "

    [blocks.segments.properties]
    branch_max_length = 25
    fetch_status = true
    fetch_upstream_icon = true

  [[blocks.segments]]
  type = "root"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = ""
  foreground = "p:white"
  background = "p:grey"
  template = "  "

  [[blocks.segments]]
  type = "status"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = ""
  foreground = "p:white"
  background = "p:blue"
  background_templates = [ "{{ if gt .Code 0 }}p:red{{ end }}" ]
  template = " {{ if gt .Code 0 }}{{ else }}{{ end }} "

    [blocks.segments.properties]
    always_enabled = true

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "text"
  foreground = "p:white"
  template = "❯"

[transient_prompt]
foreground = "p:white"
background = "transparent"
template = "❯ "

[secondary_prompt]
foreground = "p:white"
background = "transparent"
template = ""

[palette]
black = "#1D202F"
grey = "#414868"
dark_blue = "#4B6495"
blue = "#7AA2F7"
green = "#91C856"
orange = "#FF8B47"
red = "#db4b4b"
white = "#E0DEF4"
yellow = "#F3AE35"

